name: Setup Claude Code
description: Setup Claude Code CLI with GitHub Actions cache support
branding:
  icon: terminal
  color: orange

inputs:
  version:
    description: 'Claude Code version to install. Options: "stable" (recommended), "latest", or specific version number (e.g., "2.0.25")'
    required: false
    default: latest
  github_token:
    description: 'GitHub token for accessing plugin repositories. Used to configure git credentials and convert SSH URLs to HTTPS. The token is configured with the local git config. For private repositories, ensure the token has appropriate access. Learn more about creating and using encrypted secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets'
    required: false
    default: ${{ github.token }}
  marketplaces:
    description: 'Plugin marketplace sources to add. Supports: GitHub (owner/repo), Git URL, local path, or remote URL. Can be comma-separated or newline-separated for multiple marketplaces. Required if installing plugins.'
    required: false
  plugins:
    description: 'List of plugins to install. Can be comma-separated or newline-separated (e.g., "dev-tools@passionfactory,pr-review-toolkit@passionfactory" or one per line). Requires marketplaces to be added first.'
    required: false

outputs:
  cache-hit:
    description: Whether cache was restored (true/false)
  version:
    description: Installed Claude Code version
  claude-path:
    description: Absolute path to claude executable
  marketplaces_added:
    description: Number of marketplaces added or updated
  plugins_installed:
    description: Comma-separated list of successfully installed plugins

runs:
  using: node24
  main: dist/index.js
- name: Install Claude Code

  uses: pleaseai/setup-claude-code@v1.1.4