name: Install Claude Code
description: Install Claude Code CLI with GitHub Actions cache support
branding:
  icon: terminal
  color: orange

inputs:
  version:
    description: 'Claude Code version to install. Options: "stable" (recommended), "latest", or specific version number (e.g., "2.0.25")'
    required: false
    default: latest
  marketplaces:
    description: 'Plugin marketplace sources to add. Supports: GitHub (owner/repo), Git URL, local path, or remote URL. Can be comma-separated or newline-separated for multiple marketplaces. Required if installing plugins.'
    required: false
  plugins:
    description: 'List of plugins to install. Can be comma-separated or newline-separated (e.g., "dev-tools@passionfactory,pr-review-toolkit@passionfactory" or one per line). Requires marketplaces to be added first.'
    required: false

outputs:
  cache-hit:
    description: Whether cache was restored (true/false)
  version:
    description: Installed Claude Code version
  claude-path:
    description: Absolute path to claude executable
  marketplaces_added:
    description: Number of marketplaces added or updated
  plugins_installed:
    description: Comma-separated list of successfully installed plugins

runs:
  using: node24
  main: dist/index.js
